# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       json-c

# >> macros
# << macros

Summary:    A JSON implementation in C
Version:    0.12
Release:    0
Group:      Multimedia/PulseAudio
License:    MIT
URL:        http://oss.metaparadigm.com/json-c/
Source0:    http://oss.metaparadigm.com/json-c/%{name}-%{version}.tar.gz
Source100:  json-c.yaml
Patch0:     json-c-0.12-remove-unused-but-set-var.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description
JSON-C implements a reference counting object model that allows you to
easily construct JSON objects in C, output them as JSON formatted strings
and parse JSON formatted strings back into the C representation of JSON
objects.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.



%prep
%setup -q -n %{name}-%{version}
# json-c-0.12-remove-unused-but-set-var.patch
%patch0 -p1

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_libdir}/*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/json-c/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
# << files devel
